#!/usr/bin/env bash
# install nginx

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

str="\nfrontend http_web *:80\n\tbind *:80\n\tdefault_backend custom_backend\n\nbackend custom_backend\n\tbalance roundrobin\n\tserver web01 54.226.144.7:80 check\n\tserver web02 18.205.25.248:80 check"

sudo echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg
sudo servce haproxy restart
