#!/usr/bin/env bash
# this script prints Holberton School 10 times but also Hi after the 9th
END=10
x=$END
while [ $x -gt 0 ]
do
    if [ $x -eq 3 ]
    then
	echo "good luck"
    elif [ $x -eq 7 ]
    then
	echo "bad luck"
    else
	echo "Holberton School"
    fi
    x=$((x-1))
done
