#!/usr/bin/env bash
# this script prints Holberton School 10 times but also Hi after the 9th
START=1
x=$START
while [ $x -lt 20 ]
do
    echo "$x"
    case $x in
	4)
	    echo "bad luck in China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    x=$((x+1))
done
